version: '3'

services:
  js-server:
    image: node:16-alpine
    container_name: js-server
    user: node
    tty: true
    stdin_open: true
    environment:
      PORT: 3000
    ports:
      - 3000:3000
      - 4000:4000
      - 9229:9229
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
